# LaTeX2HTML 96.1 (Feb 5, 1996)
# Associate images original text with physical files.

$key = q/{_inline}$alpha_3=r-alpha_1-alpha_2${_inline}/;
$cached_env_img{$key} = ' <IMG WIDTH=137 HEIGHT=20 ALIGN=MIDDLE ALT="tex2html_wrap_inline159" SRC="img17.gif"  > '; 
$key = q/{_inline}$(r>1)${_inline}/;
$cached_env_img{$key} = ' <IMG WIDTH=33 HEIGHT=30 ALIGN=MIDDLE ALT="tex2html_wrap_inline205" SRC="img35.gif"  > '; 
$key = q/{_inline}$c_1${_inline}/;
$cached_env_img{$key} = ' <IMG WIDTH=13 HEIGHT=18 ALIGN=MIDDLE ALT="tex2html_wrap_inline119" SRC="img3.gif"  > '; 
$key = q/{_inline}$ln(p_1^ast)=ln(p_1)-ln(p_3)${_inline}/;
$cached_env_img{$key} = ' <IMG WIDTH=188 HEIGHT=30 ALIGN=MIDDLE ALT="tex2html_wrap_inline165" SRC="img20.gif"  > '; 
$key = q/{_inline}$beta_y=1r${_inline}/;
$cached_env_img{$key} = ' <IMG WIDTH=70 HEIGHT=31 ALIGN=MIDDLE ALT="tex2html_wrap_inline171" SRC="img23.gif"  > '; 
$key = q/{displaymath}ln(C)=ln(k)+(1r)ln(y)+(alpha_1r)ln(p_1)+(alpha_2r)ln(p_2)+(alpha_3r)ln(p_3)+v_t.{displaymath}/;
$cached_env_img{$key} = ' <IMG WIDTH=620 HEIGHT=20 ALIGN=BOTTOM ALT="displaymath181" SRC="img27.gif"  > '; 
$key = q/{_inline}$ln(p_2^ast)=ln(p_2)-ln(p_3)${_inline}/;
$cached_env_img{$key} = ' <IMG WIDTH=188 HEIGHT=30 ALIGN=MIDDLE ALT="tex2html_wrap_inline167" SRC="img21.gif"  > '; 
$key = q/{_inline}$c_t${_inline}/;
$cached_env_img{$key} = ' <IMG WIDTH=12 HEIGHT=18 ALIGN=MIDDLE ALT="tex2html_wrap_inline117" SRC="img2.gif"  > '; 
$key = q/{displaymath}ln(c_t)=ln(c_1)+alpha_cln(n_t)+u_t.{displaymath}/;
$cached_env_img{$key} = ' <IMG WIDTH=375 HEIGHT=20 ALIGN=BOTTOM ALT="displaymath129" SRC="img8.gif"  > '; 
$key = q/{_inline}$ln(C^ast)=ln(C)-ln(p_3)${_inline}/;
$cached_env_img{$key} = ' <IMG WIDTH=191 HEIGHT=30 ALIGN=MIDDLE ALT="tex2html_wrap_inline163" SRC="img19.gif"  > '; 
$key = q/{_inline}$r,alpha_1,alpha_2,alpha_3${_inline}/;
$cached_env_img{$key} = ' <IMG WIDTH=90 HEIGHT=18 ALIGN=MIDDLE ALT="tex2html_wrap_inline177" SRC="img26.gif"  > '; 
$key = q/{_inline}$C_t'${_inline}/;
$cached_env_img{$key} = ' <IMG WIDTH=18 HEIGHT=29 ALIGN=MIDDLE ALT="tex2html_wrap_inline191" SRC="img32.gif"  > '; 
$key = q/{_inline}$beta_0=ln(k)${_inline}/;
$cached_env_img{$key} = ' <IMG WIDTH=82 HEIGHT=30 ALIGN=MIDDLE ALT="tex2html_wrap_inline169" SRC="img22.gif"  > '; 
$key = q/{displaymath}y=Atimesx_1^alpha_1timesx_2^alpha_2timesx_3^alpha_3,{displaymath}/;
$cached_env_img{$key} = ' <IMG WIDTH=351 HEIGHT=19 ALIGN=BOTTOM ALT="displaymath133" SRC="img10.gif"  > '; 
$key = q/{displaymath}c_t=c_1n_t^alpha_ce^u_t,{displaymath}/;
$cached_env_img{$key} = ' <IMG WIDTH=303 HEIGHT=19 ALIGN=BOTTOM ALT="displaymath115" SRC="img1.gif"  > '; 
$key = q/{_inline}$x_i${_inline}/;
$cached_env_img{$key} = ' <IMG WIDTH=15 HEIGHT=18 ALIGN=MIDDLE ALT="tex2html_wrap_inline139" SRC="img11.gif"  > '; 
$key = q/{_inline}$r=sumalpha_i.${_inline}/;
$cached_env_img{$key} = ' <IMG WIDTH=75 HEIGHT=26 ALIGN=MIDDLE ALT="tex2html_wrap_inline147" SRC="img13.gif"  > '; 
$key = q/{_inline}$n_t${_inline}/;
$cached_env_img{$key} = ' <IMG WIDTH=16 HEIGHT=18 ALIGN=MIDDLE ALT="tex2html_wrap_inline121" SRC="img4.gif"  > '; 
$key = q/{displaymath}ln(C_t')=ln(k')+(alpha_cr)ln(n_t)+1rln(y_t)+u_t.{displaymath}/;
$cached_env_img{$key} = ' <IMG WIDTH=443 HEIGHT=20 ALIGN=BOTTOM ALT="displaymath189" SRC="img31.gif"  > '; 
$key = q/{displaymath}k=r(Aalpha_1^alpha_1alpha_2^alpha_2alpha_3^alpha_3)^-1r.{displaymath}/;
$cached_env_img{$key} = ' <IMG WIDTH=346 HEIGHT=23 ALIGN=BOTTOM ALT="displaymath157" SRC="img16.gif"  > '; 
$key = q/{_inline}$alpha_c${_inline}/;
$cached_env_img{$key} = ' <IMG WIDTH=17 HEIGHT=18 ALIGN=MIDDLE ALT="tex2html_wrap_inline123" SRC="img5.gif"  > '; 
$key = q/{_inline}$u_t${_inline}/;
$cached_env_img{$key} = ' <IMG WIDTH=16 HEIGHT=18 ALIGN=MIDDLE ALT="tex2html_wrap_inline125" SRC="img6.gif"  > '; 
$key = q/{displaymath}GNPD_t=(alpha_1r)ln_(p_1)+(alpha_2r)ln_(p_2)+(alpha_3r)ln_(p_3).{displaymath}/;
$cached_env_img{$key} = ' <IMG WIDTH=477 HEIGHT=21 ALIGN=BOTTOM ALT="displaymath187" SRC="img30.gif"  > '; 
$key = q/{_inline}$y_t${_inline}/;
$cached_env_img{$key} = ' <IMG WIDTH=14 HEIGHT=18 ALIGN=MIDDLE ALT="tex2html_wrap_inline203" SRC="img34.gif"  > '; 
$key = q/{_inline}$epsilon_t${_inline}/;
$cached_env_img{$key} = ' <IMG WIDTH=12 HEIGHT=17 ALIGN=MIDDLE ALT="tex2html_wrap_inline127" SRC="img7.gif"  > '; 
$key = q/{_inline}$alpha_i${_inline}/;
$cached_env_img{$key} = ' <IMG WIDTH=15 HEIGHT=18 ALIGN=MIDDLE ALT="tex2html_wrap_inline143" SRC="img12.gif"  > '; 
$key = q/{displaymath}C=k,y^1rp_1^alpha_1rp_2^alpha_2rp_3^alpha_3r,{displaymath}/;
$cached_env_img{$key} = ' <IMG WIDTH=351 HEIGHT=24 ALIGN=BOTTOM ALT="displaymath155" SRC="img15.gif"  > '; 
$key = q/{_inline}$beta_1=alpha_1r${_inline}/;
$cached_env_img{$key} = ' <IMG WIDTH=80 HEIGHT=30 ALIGN=MIDDLE ALT="tex2html_wrap_inline173" SRC="img24.gif"  > '; 
$key = q/{_inline}$beta_2=alpha_2r${_inline}/;
$cached_env_img{$key} = ' <IMG WIDTH=80 HEIGHT=30 ALIGN=MIDDLE ALT="tex2html_wrap_inline175" SRC="img25.gif"  > '; 
$key = q/{_inline}$A_t${_inline}/;
$cached_env_img{$key} = ' <IMG WIDTH=19 HEIGHT=28 ALIGN=MIDDLE ALT="tex2html_wrap_inline183" SRC="img28.gif"  > '; 
$key = q/{_inline}$C=sum_ip_ix_i${_inline}/;
$cached_env_img{$key} = ' <IMG WIDTH=94 HEIGHT=28 ALIGN=MIDDLE ALT="tex2html_wrap_inline149" SRC="img14.gif"  > '; 
$key = q/{_inline}$alpha_t${_inline}/;
$cached_env_img{$key} = ' <IMG WIDTH=16 HEIGHT=18 ALIGN=MIDDLE ALT="tex2html_wrap_inline131" SRC="img9.gif"  > '; 
$key = q/{displaymath}ln(C^ast)=beta_0+beta_yln(y)+beta_1ln(p_1^ast)+beta_2ln(p_2^ast),{displaymath}/;
$cached_env_img{$key} = ' <IMG WIDTH=433 HEIGHT=21 ALIGN=BOTTOM ALT="displaymath161" SRC="img18.gif"  > '; 
$key = q/{displaymath}ln(c_t)=ln(k')+(alpha_cr)ln(n_t)+((1-r)r)ln(y_t)+u_t,{displaymath}/;
$cached_env_img{$key} = ' <IMG WIDTH=471 HEIGHT=20 ALIGN=BOTTOM ALT="displaymath193" SRC="img33.gif"  > '; 
$key = q/{_inline}$A_t=n_t^-alpha_c${_inline}/;
$cached_env_img{$key} = ' <IMG WIDTH=80 HEIGHT=30 ALIGN=MIDDLE ALT="tex2html_wrap_inline185" SRC="img29.gif"  > '; 

1;

