#!/bin/bash
# to use this, put the category_names you want as the very last line before the final "this does the work"

# put the words (at least 3 of which must be found) into category names, and then run "colors.R"

# should at least dump it if it starts with a '#'
file=` grep read.csv colors.R |grep all.words |cut -f2 -d'"'`   # this is a bit evil

# TODO: store names a comma-delimited list, and generate the grep command

category_names='("purple"|"red"|"blue"|"green"|"yellow")'
category_names='("black"|"white"|"blue"|"red"|"yellow")'
# colors: perfect separation
category_names='("purple"|"red"|"blue"|"green"|"yellow"|"I"|"you"|"he"|"she")'

# does not find enough to be interesting, plus smile is often a noun
category_names='("cry"|"laugh"|"frown"|"smile"|"snarl"|"sneer")'

# pronouns: divides by part of speech (need "hers"?)
category_names='("i"|"you"|"he"|"she"|"they"|"we"|"us"|"them"|"him"|"her"|"our"|"his")'
# not so clear
category_names='("his"|"her"|"my"|"their"|"our"|"your"|"a"|"the"|"some")'
# "her" has multiple labels?
category_names='("I"|"you"|"she"|"he"|"we"|"they")'

# dimensions = positive/negative and mild/extreme???
category_names='("good"|"bad"|"terrible"|"horrible"|"great"|"wonderful"|"mediocre"|"fanstastic")'
# poor adequate  awesome, outstanding (ambiguous) "miserable" (different POS's)

# months: might have signal? but not much
category_names='("january"|"february"|"march"|"april"|"june"|"july"|"august"|"september"|"october"|"november"|"december")'
category_names='("february"|"july"|"august"|"august"|"september"|"october"|"november"|"december")'
# "may" is ambigous (what about "march"?) january seems to be an outlier; why?

# divides nouns and verbs
category_names='("house"|"river"|"cat"|"car"|"sleep"|"eat"|"push")'
category_names='("house"|"home"|"dog"|"truck"|"boat"|"word"|"river"|"cat"|"car"|"sleep"|"eat"|"push"|"drink"|"listen"|"carry"|"talk"|"disagree"|"agree")'

# looks OK
category_names='("tree"|"forest"|"shrub"|"orchid"|"rock"|"stone"|"dirt")'
# too bad we don't have "shrub" or "orchid"
# is "bush" ambigous? ("flower" needs POS)

# sizes: this does not look good
category_names='("small"|"large"|"tiny"|"huge"|"big"|"colossal"|"giant"|"little")'
# "medium" looks different?

# numbers: not bad!
category_names='("1"|"2"|"3"|"4"|"5"|"6"|"7"|"8"|"9"|"10"|"11"|"12"|"13"|"14"|"20"|"21")'
# numbers (as words): perfect first two PCs; not bad now
category_names='("one"|"two"|"three"|"four"|"five"|"six"|"seven"|"eight"|"nine"|"ten")'
category_names='("one"|"two"|"three"|"four"|"five"|"six"|"seven"|"eight"|"nine"|"ten"|"1"|"2"|"3"|"4"|"5"|"6"|"7"|"8"|"9"|"10")'

# gives decent separation of sports and business
# "fire" is ambiguous, as is "dive"
category_names='("hire"|"purchase"|"hit"|"swim"|"jump"|"throw"|"catch"|"buy"|"sell"|"purchase"|"trade"|"exchange")'
category_names='("hockey"|"baseball"|"soccer"|"golf"|"basketball"|"goalie"|"money"|"dollars"|"euro"|"hire"|"yen"|"purchase"|"hit"|"swim"|"jump"|"throw"|"catch"|"buy"|"sell"|"ibm"|"purchase"|"leverage"|"trade"|"exchange"|"profit"|"price")'

# sizes are random (because some are absolutes and some are are relative?)
category_names='("little"|"tiny"|"huge"|"big"|"small"|"large"|"colossal"|"giant"|"medium-sized"|"undersized"|"enormous"|"microscopic")'
# "little" is a different POS

# years: works nicely
category_names='("1995"|"1996"|"1997"|"1998"|"1999"|"2000"|"2001"|"2002"|"2003"|"2004"|"2005"|"2006"|"2007"|"2008"|"2009")'

# female names
category_names='("mary"|"patricia"|"tricia"|"linda"|"barbara"|"elizabeth"|"liz"|"betsy"|"jennifer"|"maria"|"susan"|"margaret"|"dorothy"|"lisa"|"nancy"|"karen"|"betty"|"helen")'

# male names
category_names='("john"|"robert"|"bob"|"michael"|"mike"|"william"|"david"|"richard"|"charles"|"joseph"|"joe"|"thomas"|"tom"|"christopher"|"daniel"|"dan"|"paul"|"donald"|"don"|"george")'     
# can't use "bill" or "dick"

# male and female names: gives decent separation
category_names='("mary"|"patricia"|"tricia"|"linda"|"barbara"|"elizabeth"|"liz"|"betsy"|"jennifer"|"maria"|"susan"|"margaret"|"dorothy"|"lisa"|"nancy"|"karen"|"betty"|"helen"|"john"|"robert"|"bob"|"michael"|"mike"|"william"|"david"|"richard"|"charles"|"joseph"|"joe"|"thomas"|"tom"|"christopher"|"daniel"|"dan"|"paul"|"donald"|"george")'     
# better to drop "bob", "don", maybe "joe"??

# emotions: no signal? - does not currently find most of the words
category_names='("happy"|"sad"|"mad"|"angry"|"lonely")'
category_names='("happy"|"joyous"|"pleased"|"sad"|"miserable"|"displeased"|"unhappy"|"angry")'
category_names='("happiness"|"joy"|"pleasure"|"sadness"|"misery"|"displeasure"|"unhappiness"|"anger")'
# emotions these work badly
category_names='("anger"|"fear"|"disgust"|"happiness"|"sadness"|"surprise"|"amusement"|"contempt"|"contentment"|"embarrassment"|"excitement"|"guilt"|"relief"|"satisfaction"|"shame")'
category_names='("anger"|"fear"|"disgust"|"happiness"|"sadness"|"surprise")'
# emotions: try removing the ones that can be verbs: fear, disgust, surprise (
category_names='("anger"|"happiness"|"sadness"|"amusement"|"contempt"|"contentment"|"embarrassment"|"excitement"|"guilt"|"relief"|"satisfaction"|"shame")'
# emotions: also note that we "get" "relief" and "satisfaction", but not the others  -- still crappy
category_names='("anger"|"happiness"|"sadness"|"amusement"|"contempt"|"contentment"|"embarrassment"|"excitement"|"guilt"|"shame")'

# zip codes: none of these are found
category_names='("10650"|"12401"|"21701"|"30309"|"30324"|"32801"|"55057"|"60611"|"90046"|"92130")'

# birds: good
category_names='("bluejay"|"parrot"|"blackbird"|"eagle"|"hummingbird"|"pigeon"|"wren"|"pelican"|"parakeet"|"finch")'
# animals: interesting, but why is cow near mouse?
category_names='("dog"|"cat"|"mouse"|"rat"|"horse"|"cow"|"giraffe"|"zerbra"|"elephant"|"hamster"|"tiger"|"monkey")'
# insects plural: works great excipet lice
category_names='("ants"|"aphids"|"lice"|"fleas"|"spiders"|"beetles"|"moths"|"houseflies"|"weevils"|"caterpillars")'
# insects singular
category_names='("ant"|"aphid"|"louse"|"flea"|"spider"|"beetle"|"moth"|"housefly"|"weevil"|"caterpillar")'

# materials dont work
category_names='("steel"|"iron"|"copper"|"brass"|"wood"|"plastic"|"aluminum")'

# letters dont work
category_names='("a"|"b"|"c"|"d"|"e"|"f"|"g")'

# lengths dont work
category_names='("inch"|"foot"|"mile"|"cm"|"meter"|"km")'

# words not in to 10k
category_names='("happy"|"sad"|"depression"|"ecstatic"|"unhappy")'

#  Seperates into initials and real words
category_names='("feb"|"apr"|"jul"|"jun"|"aug"|"sept"|"oct"|"nov"|"february"|"march"|"april"|"june"|"july"|"august"|"september"|"october"|"november"|"december")'

# at least mouse and rat are close
category_names='("dog"|"cat"|"mouse"|"rat"|"elephant"|"horse"|"cow"|"giraffe"|"zerbra"|"elephant"|"hamster")'
category_names='("dog"|"cat"|"mouse"|"rat"|"gerbil"|"hamster")'

# doesn't find enough for any words to be similar
category_names='("gun"|"pistol"|"rifle"|"weapon"|"bomb"|"grenade"|"bullet"|"missle"|"rocket")'

category_names='("four"|"red"|"mouse"|"gun"|"president"|"big"|"coat")'

# leaders -- too diverse
category_names='("bishop"|"pope"|"president"|"senantor"|"congressman"|"chairman"|"leader"|"vice-president"|"secretary"|"commander"|"chief"|"officer"|"aide"|"manager")'
# this looks reasonable
category_names='("bishop"|"pope"|"president"|"senantor"|"congressman"|"chairman"|"vice-president"|"commander"|"chief")'
category_names='(bishop"|"pope"|"deacon"|"rabbi"|"president"|"senator"|"congressman"|"chairman"|"vice-president"|"mayor"|"governor")'
#

# sweet vs savory - OK
category_names='("pudding"|"cake"|"cookie"|"candy"|"dessert"|"cheesecake"|"hamburger"|"steak"|"lasagna"|"pizza"|"chicken"|"pork")'

# food vs not food
category_names='("carrot"|"lettuce"|"hamburger"|"steak"|"sandwich"|"salad"|"coat"|"hat"|"gloves"|"mittens")'
category_names='("carrots"|"lettuce"|"hamburger"|"steak"|"sandwich"|"salad"|"coke"|"pepsi"|"wine"|"lemonade"|"coffee"|"tea"|"juice"|"milk")'
# too many dimensions to capture
category_names='("carrots"|"lettuce"|"hamburger"|"steak"|"sandwich"|"salad"|"coke"|"pepsi"|"wine"|"lemonade"|"coffee"|"tea"|"juice"|"milk")'

# animate vs inamimate
category_names='("woman"|"man"|"girl"|"boy"|"dog"|"cat"|"elephant"|"hat"|"glove"|"coat"|"book"|"computer"|"paper"|"pen"|"pencil")'

# vehicles -- no signal?
category_names='("car"|"truck"|"airplane"|"helicopter"|"rocket"|"boat"|"sailboat"|"canoe"|"kayak"|"missile"|"motorcycle"|"bicycle")'
# "ship" and "train" are verbs!!!! "plane" is ambiguous

# THE CURRENT ONE BEING USED

category_names='("home"|"truck"|"boat"|"word"|"river"|"cat"|"car"|"sleep"|"eat"|"push"|"drink"|"listen"|"carry"|"talk"|"disagree"|"agree")'
category_names='("one"|"two"|"three"|"four"|"five"|"six"|"seven"|"eight"|"nine"|"ten")'
category_names='("i"|"you"|"he"|"she"|"they"|"we"|"us"|"them"|"him"|"her"|"our"|"his")'
category_names='("carrots"|"lettuce"|"hamburger"|"steak"|"sandwich"|"salad"|"coke"|"pepsi"|"wine"|"lemonade"|"coffee"|"tea"|"juice"|"milk")'

category_names='("mary"|"patricia"|"tricia"|"linda"|"barbara"|"elizabeth"|"liz"|"betsy"|"jennifer"|"maria"|"susan"|"margaret"|"dorothy"|"lisa"|"nancy"|"karen"|"betty"|"helen"|"john"|"robert"|"bob"|"michael"|"mike"|"william"|"david"|"richard"|"charles"|"joseph"|"joe"|"thomas"|"tom"|"christopher"|"daniel"|"dan"|"paul"|"donald"|"george")'     



################ This LINE DOES THE WORK ####################
cat <(head -1 $file) <(egrep $category_names $file) 
####################################


