#!/bin/sh

touch 'parse csv was here'

dos2unix < data > data.unix
../../csv_parser --input-file=data.unix --output-file=model > csv_parse_output
../../build_model --input-file=model --output-path=log/ -r $1  > latest_pretty
